function footers() {
    return `<footer class="footer" id="footer">
      <div class="container">
              <div class="options">
                          <div class="footer-opt">
                                        <h4>AYUDA</h4>
                                                      <ul>
                                                                        <li><a href="https://www.creamconcept.com.ar/" target="_blank">COMPRAR EN CREAMCONCEPT.COM.AR</a></li>
                                                                                          <li><a href="./products.html">PRODUCTOS</a></li>
                                                                                                            <li><a href="https://www.creamconcept.com.ar/paginas/guia-de-talles" target="_blank">GUÍA DE TALLES</a></li>
                                                                                                                              <li><a href="https://www.creamconcept.com.ar/paginas/como-comprar" target="_blank">CÓMO COMPRAR</a></li>
                                                                                                                                                <li><a href="https://www.creamconcept.com.ar/paginas/politica-de-cambios-y-devoluciones" target="_blank">CAMBIOS Y DEVOLUCIONES</a></li>
                                                                                                                                                                  <li><a href="https://www.creamconcept.com.ar/paginas/quienes-somos" target="_blank">QUIÉNES SOMOS</a></li>
                                                                                                                                                                                    <li><a href="./login.html">MI CUENTA</a></li>
                                                                                                                                                                                                  </ul>
                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                          <div class="footer-opt">
                                                                                                                                                                                                                                        <h4>SEGUINOS</h4>
                                                                                                                                                                                                                                                      <ul>
                                                                                                                                                                                                                                                                        <li><a href="*">NEWSLETTER</a></li>
                                                                                                                                                                                                                                                                                          <li><a href="*">TIKTOK</a></li>
                                                                                                                                                                                                                                                                                                            <li><a href="*">INSTAGRAM</a></li>
                                                                                                                                                                                                                                                                                                                              <li><a href="*">FACEBOOK</a></li>
                                                                                                                                                                                                                                                                                                                                                <li><a href="*">WHATSAPP</a></li>
                                                                                                                                                                                                                                                                                                                                                              </ul>
                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                      <div class="footer-opt">
                                                                                                                                                                                                                                                                                                                                                                                                    <h4>CREAM CONCEPT</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                  <ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <li><a href="https://www.creamconcept.com.ar/paginas/quienes-somos" target="_blank">QUIÉNES SOMOS</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <li><a href="https://www.creamconcept.com.ar/paginas/contacto" target="_blank">CONTACTO</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="footer-opt">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h4>POLÍTICAS</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <li><a href="*">POLÍTICA DE PRIVACIDAD</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li><a href="*">CONDICIONES DE COMPRA</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <li><a href="*">CONFIGURACIÓN DE COOKIES</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <hr id="line">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div class="divfoot">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div id="div1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <p>ARGENTINA</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <div id="div2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>ESPAÑOL</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p id="reserved">© CREAM CONCEPT — TODOS LOS DERECHOS RESERVADOS</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <p id="end">Sitio no oficial adaptado a modo de ejemplo a partir del catálogo público de creamconcept.com.ar</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </footer>`;
}
export { footers };
